name: family_bottom_sheet
description: A package for building smooth, customizable multi-page bottom sheets with seamless transitions — just like a Navigator, but inside a bottom sheet.
version: 0.0.1
repository: https://github.com/danielkiing3/family_bottom_sheet

topics:
  - ui
  - widget
  - bottom-sheet
  - custom-modal

screenshots:
  - description: 'Example of family_bottom_sheet'
    path: doc/family_modal_sheet.gif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
